SUPABASE_URL = "https://isrzxefziojidmacpihl.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlzcnp4ZWZ6aW9qaWRtYWNwaWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNjI1OTksImV4cCI6MjA3MDkzODU5OX0.PziVLF9K7A3It0K_bxlhz1oSx6a-Pr9Qgr3sWHzWnCc"
